// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rpssl.Infrastructure.Database;

#nullable disable

namespace Rpssl.Infrastructure.Migrations
{
    [DbContext(typeof(RpsslDbContext))]
    [Migration("20250811071544_SeedChoiceTable")]
    partial class SeedChoiceTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rpssl.Domain.Entities.Choice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Choices", (string)null);
                });

            modelBuilder.Entity("Rpssl.Domain.Entities.GameResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ComputerChoiceId")
                        .HasColumnType("int");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset>("PlayedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("PlayerChoiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComputerChoiceId");

                    b.HasIndex("Outcome");

                    b.HasIndex("PlayedAt");

                    b.HasIndex("PlayerChoiceId");

                    b.ToTable("GameResults", (string)null);
                });

            modelBuilder.Entity("Rpssl.Domain.Entities.GameResult", b =>
                {
                    b.HasOne("Rpssl.Domain.Entities.Choice", "ComputerChoice")
                        .WithMany()
                        .HasForeignKey("ComputerChoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Rpssl.Domain.Entities.Choice", "PlayerChoice")
                        .WithMany()
                        .HasForeignKey("PlayerChoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ComputerChoice");

                    b.Navigation("PlayerChoice");
                });
#pragma warning restore 612, 618
        }
    }
}
